### ISSUE TITLE
Min. Cycle time for RPI?

### ISSUE THREAD

**Issue by vChavezB** [Pinetek-Networks/iol-hat#1]
I was wondering if you have done tests on what is the lowest cycle time you can achieve with the RPI without RT-patch ?

Btw this seems like a nice project 👍

**Comment by anla-pinetek** [comment]
Cycle time depends on the COM speed and the actual layout of the process data of the device. Measurements have shown that the minimum theoretical cycle time can be achieved for COM2 (~10ms cycle time) without communication breaks (Master application on dedicated core, Raspberry Pi 4).
